hylog.lo: /home/frost/projects/php-7.0.5/ext/hylog/hylog.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/frost/projects/php-7.0.5/ext/hylog $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/frost/projects/php-7.0.5/ext/hylog/hylog.c -o hylog.lo 
$(phplibdir)/hylog.la: ./hylog.la
	$(LIBTOOL) --mode=install cp ./hylog.la $(phplibdir)

./hylog.la: $(shared_objects_hylog) $(HYLOG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_hylog) $(HYLOG_SHARED_LIBADD)

